### ISSUE TITLE
在设置-扩展中没有Swimat的选项

### ISSUE THREAD

**Issue by tonyHu08** [Jintin/Swimat#198]
很喜欢这个插件，用了一段时间后突然失效，在设置中没有swimat的选项，xcode中也没有，重新安装数次无果，谢谢！

**Comment by Jintin** [comment]
可以請問你是否有更新作業系統 或是更新我們的 app 呢?
可不可以提供給我們你的 os 版本 目前使用 app 的版本
讓我們檢查看看是否有問題?
或許可以試試安裝舊的版本 https://github.com/Jintin/Swimat/releases
或者是從 source code build 自己的版本
如果有進一步的消息麻煩再跟我們回應 謝謝

**Comment by tonyHu08** [comment]
感谢你的回复！我的操作系统os版本是10.4.2，Xcode版本为10.1，不同版本的swimat都尝试过了，usr/local/bin中的swimat文件也删除并重新安装过了，设置扩展中依然没有对应的选项。

**Comment by tonyHu08** [comment]
刚刚尝试安装了旧版本（9.4.1）解决了这个问题！

**Comment by Jintin** [comment]
應該是 os 太舊所以新版本的無法支援
感謝你的回覆 祝你使用愉快!

**Comment by saagarjha** [comment]
(I have been following this thread via Google Translate, so I apologize if I am making any erroneous assumptions)

> 我的操作系统os版本是10.4.2

Is this a typo for 10.14.2? If so,

> 應該是 os 太舊所以新版本的無法支援

we should support this version, obviously. The underlying issue is that the plugin discovery mechanism is flaky and we don't have a good way of telling it to pick up Swimat other than the hack I described in #195.
