### ISSUE TITLE
Hot key suggestion?

### ISSUE THREAD

**Issue by JulesMoorhouse** [Jintin/Swimat#208]
It would be awesome if you could suggest a hot key, then most people would use it and it would be easier globally say in tutorials to use the same key etc.

?

**Comment by JulesMoorhouse** [comment]
Hmmm how about command + `

**Comment by Jintin** [comment]
I've update the README to ⌘ + ⇧ + L .
Reason is because I use IntelliJ(Android Studio) for years and the default hot key is this. And this is also the reason Swimat been created since I can't live without an IDE format tool when I learn iOS development. But it's not a hard rule, you can set what ever you like.
https://github.com/Jintin/Swimat#usage
